window.env = {
  "ACSetupSvcPort": "23210",
  "ACSvcPort": "17532",
  "ALLUSERSPROFILE": "C:\\ProgramData",
  "APPDATA": "C:\\Users\\Antônio\\AppData\\Roaming",
  "ChocolateyInstall": "C:\\ProgramData\\chocolatey",
  "ChocolateyLastPathUpdate": "133276398189783869",
  "CHROME_CRASHPAD_PIPE_NAME": "\\\\.\\pipe\\LOCAL\\crashpad_18376_VFFBBPQJRRMLRVOI",
  "COLOR": "1",
  "COLORTERM": "truecolor",
  "COLUMNS": "202",
  "CommonProgramFiles": "C:\\Program Files\\Common Files",
  "CommonProgramFiles(x86)": "C:\\Program Files (x86)\\Common Files",
  "CommonProgramW6432": "C:\\Program Files\\Common Files",
  "COMPUTERNAME": "DESKTOP-5DNPK7M",
  "ComSpec": "C:\\WINDOWS\\system32\\cmd.exe",
  "DriverData": "C:\\Windows\\System32\\Drivers\\DriverData",
  "EDITOR": "C:\\WINDOWS\\notepad.exe",
  "EFC_7624": "1",
  "FPS_BROWSER_APP_PROFILE_STRING": "Internet Explorer",
  "FPS_BROWSER_USER_PROFILE_STRING": "Default",
  "GIT_ASKPASS": "d:\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass.sh",
  "HOME": "C:\\Users\\Antônio",
  "HOMEDRIVE": "C:",
  "HOMEPATH": "\\Users\\Antônio",
  "INIT_CWD": "D:\\GitHub\\portfolio",
  "LANG": "en_US.UTF-8",
  "LOCALAPPDATA": "C:\\Users\\Antônio\\AppData\\Local",
  "LOGONSERVER": "\\\\DESKTOP-5DNPK7M",
  "NODE": "C:\\Program Files\\nodejs\\node.exe",
  "NODE_EXE": "C:\\Program Files\\nodejs\\\\node.exe",
  "NPM_CLI_JS": "C:\\Program Files\\nodejs\\\\node_modules\\npm\\bin\\npm-cli.js",
  "npm_command": "run-script",
  "npm_config_cache": "C:\\Users\\Antônio\\AppData\\Local\\npm-cache",
  "npm_config_globalconfig": "C:\\Users\\Antônio\\AppData\\Roaming\\npm\\etc\\npmrc",
  "npm_config_global_prefix": "C:\\Users\\Antônio\\AppData\\Roaming\\npm",
  "npm_config_init_author_name": "Antonio Pacheco Gerim Ribeiro",
  "npm_config_init_module": "C:\\Users\\Antônio\\.npm-init.js",
  "npm_config_local_prefix": "D:\\GitHub\\portfolio",
  "npm_config_metrics_registry": "https://registry.npmjs.org/",
  "npm_config_node_gyp": "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js",
  "npm_config_noproxy": "",
  "npm_config_prefix": "C:\\Users\\Antônio\\AppData\\Roaming\\npm",
  "npm_config_userconfig": "C:\\Users\\Antônio\\.npmrc",
  "npm_config_user_agent": "npm/9.5.1 node/v18.16.0 win32 x64 workspaces/false",
  "npm_execpath": "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js",
  "npm_lifecycle_event": "build",
  "npm_lifecycle_script": "react-dotenv && react-scripts build",
  "npm_node_execpath": "C:\\Program Files\\nodejs\\node.exe",
  "npm_package_json": "D:\\GitHub\\portfolio\\package.json",
  "npm_package_name": "portfolio",
  "npm_package_version": "0.1.0",
  "NPM_PREFIX_NPM_CLI_JS": "C:\\Users\\Ant├┤nio\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js",
  "NUMBER_OF_PROCESSORS": "12",
  "OneDrive": "C:\\Users\\Antônio\\OneDrive",
  "ORIGINAL_XDG_CURRENT_DESKTOP": "undefined",
  "OS": "Windows_NT",
  "Path": "D:\\GitHub\\portfolio\\node_modules\\.bin;D:\\GitHub\\node_modules\\.bin;D:\\node_modules\\.bin;C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\@npmcli\\run-script\\lib\\node-gyp-bin;D:\\GitHub\\portfolio\\node_modules\\.bin;D:\\GitHub\\node_modules\\.bin;D:\\node_modules\\.bin;C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\@npmcli\\run-script\\lib\\node-gyp-bin;C:\\Program Files\\Python311\\Scripts\\;C:\\Program Files\\Python311\\;C:\\Python310\\Scripts\\;C:\\Python310\\;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\ProgramData\\chocolatey\\bin;C:\\Program Files\\dotnet\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\Docker\\Docker\\resources\\bin;C:\\ProgramData\\DockerDesktop\\version-bin;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;D:\\Programs\\Git\\cmd;C:\\Program Files\\nodejs\\;C:\\Program Files\\MySQL\\MySQL Shell 8.0\\bin\\;C:\\Users\\Antônio\\AppData\\Local\\Programs\\Python\\Python39\\Scripts\\;C:\\Users\\Antônio\\AppData\\Local\\Programs\\Python\\Python39\\;D:\\Programs\\Python3\\Scripts\\;D:\\Programs\\Python3\\;C:\\Users\\Antônio\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\Antônio\\AppData\\Local\\GitHubDesktop\\bin;D:\\Programs\\MinGW\\bin;D:\\Programs\\Git\\cmd;C:\\Users\\Antônio\\.dotnet\\tools;D:\\Programs\\Microsoft VS Code\\bin;;D:\\Programs\\PyCharm Community Edition 2022.3.2\\bin;;C:\\Program Files\\heroku\\bin;D:\\Programs\\heroku\\bin;C:\\Users\\Antônio\\AppData\\Roaming\\npm;C:\\Program Files (x86)\\Atmel\\Flip 3.4.7\\bin",
  "PATHEXT": ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JSE;.WSF;.WSH;.MSC;.PY;.PYW;.CPL",
  "PROCESSOR_ARCHITECTURE": "AMD64",
  "PROCESSOR_IDENTIFIER": "Intel64 Family 6 Model 165 Stepping 3, GenuineIntel",
  "PROCESSOR_LEVEL": "6",
  "PROCESSOR_REVISION": "a503",
  "ProgramData": "C:\\ProgramData",
  "ProgramFiles": "C:\\Program Files",
  "ProgramFiles(x86)": "C:\\Program Files (x86)",
  "ProgramW6432": "C:\\Program Files",
  "PROMPT": "$P$G",
  "PSModulePath": "C:\\Users\\Antônio\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules",
  "PUBLIC": "C:\\Users\\Public",
  "PyCharm Community Edition": "D:\\Programs\\PyCharm Community Edition 2022.3.2\\bin;",
  "Python Scripts": "C:\\Users\\Antônio\\AppData\\Roaming\\Python\\Python311\\Scripts",
  "PythonScripts": "C:\\Users\\Antônio\\AppData\\Roaming\\Python\\Python311\\Scripts",
  "RlsSvcPort": "22112",
  "SERVICE_ID": "service_19qupfj",
  "SESSIONNAME": "Console",
  "SystemDrive": "C:",
  "SystemRoot": "C:\\WINDOWS",
  "TEMP": "C:\\Users\\ANTNIO~1\\AppData\\Local\\Temp",
  "TEMPLATE_ID": "template_bjsutmh",
  "TERM_PROGRAM": "vscode",
  "TERM_PROGRAM_VERSION": "1.78.2",
  "TMP": "C:\\Users\\ANTNIO~1\\AppData\\Local\\Temp",
  "USERDOMAIN": "DESKTOP-5DNPK7M",
  "USERDOMAIN_ROAMINGPROFILE": "DESKTOP-5DNPK7M",
  "USERNAME": "Antônio",
  "USERPROFILE": "C:\\Users\\Antônio",
  "USER_ID": "7WF2j6knCp3rvTL4M",
  "VS160COMCOMNTOOLS": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\Tools\\",
  "VSCODE_GIT_ASKPASS_EXTRA_ARGS": "--ms-enable-electron-run-as-node",
  "VSCODE_GIT_ASKPASS_MAIN": "d:\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass-main.js",
  "VSCODE_GIT_ASKPASS_NODE": "D:\\Programs\\Microsoft VS Code\\Code.exe",
  "VSCODE_GIT_IPC_HANDLE": "\\\\.\\pipe\\vscode-git-c36cfcb594-sock",
  "VSCODE_INJECTION": "1",
  "windir": "C:\\WINDOWS"
};